version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python app.py
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5001:5000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 5432:5432
volumes:
  postgres_data: